### ISSUE TITLE
app links direct to share.streamlit.io

### ISSUE THREAD

**Issue by Ali-Flt** [soft-nougat/dqw-ivves#63]
I thought by running the app locally all processes will run on the local machine but after running the app using `streamlit run app.py` only the first page runs on localhost and by clicking on any options I get redirected to [https://share.streamlit.io/soft-nougat/dqw-ivves_structured/main/app.py](https://share.streamlit.io/soft-nougat/dqw-ivves_structured/main/app.py)

**Comment by soft-nougat** [comment]
Hey @Ali-Flt!

Sorry for the confusion - this is just the main app window. All the other apps are in their designated github repos linked in the readme. Please fetch the code from there. 

[Main Streamlit app 📊](https://share.streamlit.io/soft-nougat/dqw-ivves/app.py)
[Tabular Data Section 🏗️](https://share.streamlit.io/soft-nougat/dqw-ivves_structured/main/app.py)
[Audio Data Section 🎶](https://share.streamlit.io/soft-nougat/dqw-ivves_audio/main/app.py)
[Text Data Section 📚](https://share.streamlit.io/soft-nougat/dqw-ivves_text/main/app.py)
[Image Data Section 🖼️](https://share.streamlit.io/soft-nougat/dqw-ivves_images/main/app.py)
